### ISSUE TITLE
Error when running exaples

### ISSUE THREAD

**Issue by luca-dex** [caravagn/mobster#25]
At the moment R CMD check is failing when running examples. Here the error:

```
  Running examples in ‘mobster-Ex.R’ failed
  The error most likely occurred in:
  
  > ### Name: get_clone_trees
  > ### Title: Return clone trees from the fit.
  > ### Aliases: get_clone_trees

...

  > trees = get_clone_trees(x)
  Error in get_clone_trees(x) : 
    Your data should have driver events annotated, cannot use 'ctree' otherwise.
  Execution halted
```

**Comment by caravagn** [comment]
It is not a bug. I raises an error (intercepted) because `Your data should have driver events annotated, cannot use 'ctree' otherwise.` Should I not use a `stop` but rather return `NULL`?

**Comment by caravagn** [comment]
Btw which one is file `mobster-Ex.R’?

**Comment by luca-dex** [comment]
If the execution gives error means that there's something broken!
The example should be constructed in a way that it can be executed without
rising warning or error that break the execution...

mobster-Ex.R is the name of the file generated by R CMD check with the code
of all the examples when they're run

**Comment by caravagn** [comment]
Is the example built from the MAN?

**Comment by luca-dex** [comment]
file: get_clone_tree.R, line 45
function: get_clone_trees()

**Comment by caravagn** [comment]
I updated the example in commit #20110ca

**Comment by luca-dex** [comment]
Good boy!
