### ISSUE TITLE
Input specifications

### ISSUE THREAD

**Issue by SwaggerNiels** [caravagn/mobster#26]
I can't seem to find what the "d" and "popsize" are indicating in the input examples.
Could someone clarify?

**Comment by caravagn** [comment]
Hello @SwaggerNiels I am assuming you refer the vignette on clonal expansions. As stated that is a dataset simulated with our in-house simulator [TEMULATOR](https://t-heide.github.io/TEMULATOR/), it is nothing required to run mobster. The package has his own [input format, which is unrelated of the simulator](https://caravagn.github.io/mobster/articles/a1_introduction.html).

I also pushed an update of the website, it should be more clear which vignette you should be starting from.

**Comment by caravagn** [comment]
Can I close this @SwaggerNiels?

**Comment by SwaggerNiels** [comment]
Yes
